/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spot.glb -k s -T -S
Files: spot.glb [5.17MB] > /Users/stephen/Downloads/spot-transformed.glb [213.58KB] (96%)
Author: hulking292wax (https://sketchfab.com/hulking292wax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spot-spidermanidkaddtexturestosketchfab-b5410eaa8b4847b3941e2281c04fb5c8
Title: Spot - spiderman(IdkAddTexturesToSketchfab)
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { DoubleSide, MeshBasicMaterial, Plane, Vector3 } from "three";

export interface PulseUniforms {
  uTime: { value: number };
  uOrigin: { value: Vector3 };
  uAspectRatio: { value: number };
  uDarkColor: { value: number };
}

interface IProps {
  scale?: number;
  position?: Vector3;
  rotationY?: number;
  pulseUniforms: PulseUniforms;
}

const yClipPlane = new Plane(new Vector3(0, 1, 0), 1.75);

// 4D simplex noise (function names suffixed to avoid collisions)
const NOISE_GLSL = `
vec4 mod289p(vec4 x){return x-floor(x*(1.0/289.0))*289.0;}
float mod289p(float x){return x-floor(x*(1.0/289.0))*289.0;}
vec4 permutep(vec4 x){return mod289p(((x*34.0)+10.0)*x);}
float permutep(float x){return mod289p(((x*34.0)+10.0)*x);}
vec4 taylorInvSqrtp(vec4 r){return 1.79284291400159-0.85373472095314*r;}
float taylorInvSqrtp(float r){return 1.79284291400159-0.85373472095314*r;}
vec4 grad4p(float j,vec4 ip){
  const vec4 ones=vec4(1.0,1.0,1.0,-1.0);
  vec4 p,s;
  p.xyz=floor(fract(vec3(j)*ip.xyz)*7.0)*ip.z-1.0;
  p.w=1.5-dot(abs(p.xyz),ones.xyz);
  s=vec4(lessThan(p,vec4(0.0)));
  p.xyz=p.xyz+(s.xyz*2.0-1.0)*s.www;
  return p;
}
float snoisep(vec4 v){
  const vec4 C=vec4(0.138196601125011,0.276393202250021,0.414589803375032,-0.447213595499958);
  vec4 i=floor(v+dot(v,vec4(0.309016994374947451)));
  vec4 x0=v-i+dot(i,C.xxxx);
  vec4 i0;vec3 isX=step(x0.yzw,x0.xxx);vec3 isYZ=step(x0.zww,x0.yyz);
  i0.x=isX.x+isX.y+isX.z;i0.yzw=1.0-isX;
  i0.y+=isYZ.x+isYZ.y;i0.zw+=1.0-isYZ.xy;i0.z+=isYZ.z;i0.w+=1.0-isYZ.z;
  vec4 i3=clamp(i0,0.0,1.0);vec4 i2=clamp(i0-1.0,0.0,1.0);vec4 i1=clamp(i0-2.0,0.0,1.0);
  vec4 x1=x0-i1+C.xxxx;vec4 x2=x0-i2+C.yyyy;vec4 x3=x0-i3+C.zzzz;vec4 x4=x0+C.wwww;
  i=mod289p(i);
  float j0=permutep(permutep(permutep(permutep(i.w)+i.z)+i.y)+i.x);
  vec4 j1=permutep(permutep(permutep(permutep(
    i.w+vec4(i1.w,i2.w,i3.w,1.0))+i.z+vec4(i1.z,i2.z,i3.z,1.0))+
    i.y+vec4(i1.y,i2.y,i3.y,1.0))+i.x+vec4(i1.x,i2.x,i3.x,1.0));
  vec4 ip=vec4(1.0/294.0,1.0/49.0,1.0/7.0,0.0);
  vec4 p0=grad4p(j0,ip);vec4 p1=grad4p(j1.x,ip);vec4 p2=grad4p(j1.y,ip);
  vec4 p3=grad4p(j1.z,ip);vec4 p4=grad4p(j1.w,ip);
  vec4 norm=taylorInvSqrtp(vec4(dot(p0,p0),dot(p1,p1),dot(p2,p2),dot(p3,p3)));
  p0*=norm.x;p1*=norm.y;p2*=norm.z;p3*=norm.w;p4*=taylorInvSqrtp(dot(p4,p4));
  vec3 m0=max(0.6-vec3(dot(x0,x0),dot(x1,x1),dot(x2,x2)),0.0);
  vec2 m1=max(0.6-vec2(dot(x3,x3),dot(x4,x4)),0.0);
  m0=m0*m0;m1=m1*m1;
  return 49.0*(dot(m0*m0,vec3(dot(p0,x0),dot(p1,x1),dot(p2,x2)))+dot(m1*m1,vec2(dot(p3,x3),dot(p4,x4))));
}
`;

function applyPulseShader(
  mat: MeshBasicMaterial,
  uniforms: PulseUniforms,
  showInDark: boolean,
) {
  mat.onBeforeCompile = (shader) => {
    shader.uniforms.uPulseTime = uniforms.uTime;
    shader.uniforms.uPulseOrigin = uniforms.uOrigin;
    shader.uniforms.uPulseAspect = uniforms.uAspectRatio;
    shader.uniforms.uPulseDark = uniforms.uDarkColor;

    // Vertex: pass NDC position to fragment
    shader.vertexShader = shader.vertexShader.replace(
      "void main() {",
      "varying vec2 vPulseNdc;\nvoid main() {",
    );
    shader.vertexShader = shader.vertexShader.replace(
      "#include <project_vertex>",
      `#include <project_vertex>
       vPulseNdc = gl_Position.xy / gl_Position.w;`,
    );

    // Fragment: add pulse uniforms, noise, and discard logic
    shader.fragmentShader =
      `
      varying vec2 vPulseNdc;
      uniform float uPulseTime;
      uniform vec3 uPulseOrigin;
      uniform float uPulseAspect;
      uniform float uPulseDark;
      ${NOISE_GLSL}
    ` + shader.fragmentShader;

    shader.fragmentShader = shader.fragmentShader.replace(
      "#include <opaque_fragment>",
      `
      vec2 pulseUv = vPulseNdc * 0.5 + 0.5;
      float pDist = distance(
        vec2(vPulseNdc.x * uPulseAspect, vPulseNdc.y),
        vec2(uPulseOrigin.x * uPulseAspect, uPulseOrigin.y)
      );
      float pNoise = snoisep(vec4(
        vec2(pulseUv.x * 10.0, pulseUv.y * uPulseAspect * 10.0),
        uPulseTime * 0.2, uPulseTime * 0.3
      ));
      float pulse = (pDist - uPulseTime * 2.5);
      pulse += pNoise * 0.1;
      pulse = smoothstep(0.03, 0.01, pulse);
      float bgVal = mix(pulse, 1.0 - pulse, uPulseDark);
      ${showInDark ? "if (bgVal > 0.5) discard;" : "if (bgVal < 0.5) discard;"}
      #include <opaque_fragment>
      `,
    );
  };
}

export function Spot(props: IProps) {
  const { pulseUniforms, rotationY, ...rest } = props;
  const { nodes, materials } = useGLTF("/models/spot.glb") as any;

  const blackMaterials = useMemo(() => {
    const mat1 = new MeshBasicMaterial({
      color: materials.aiStandardSurface1.color,
      map: materials.aiStandardSurface1.map,
      transparent: materials.aiStandardSurface1.transparent,
      opacity: materials.aiStandardSurface1.opacity,
      side: materials.aiStandardSurface1.side,
      clippingPlanes: [yClipPlane],
    });
    applyPulseShader(mat1, pulseUniforms, false);

    const mat2 = new MeshBasicMaterial({
      color: materials.surfaceShader1.color,
      map: materials.surfaceShader1.map,
      transparent: materials.surfaceShader1.transparent,
      opacity: materials.surfaceShader1.opacity,
      side: materials.surfaceShader1.side,
      clippingPlanes: [yClipPlane],
    });
    applyPulseShader(mat2, pulseUniforms, false);

    return [mat1, mat2];
  }, [materials, pulseUniforms]);

  const whiteMaterial = useMemo(() => {
    const mat = new MeshBasicMaterial({
      map: materials.aiStandardSurface2.map,
      side: DoubleSide,
      clippingPlanes: [yClipPlane],
    });
    applyPulseShader(mat, pulseUniforms, true);
    return mat;
  }, [materials, pulseUniforms]);

  return (
    <group {...rest} rotation-y={rotationY} dispose={null}>
      {/* Black body / white spots variant */}
      <mesh
        name="The_Spot004_aiStandardSurface1_0"
        geometry={nodes.The_Spot004_aiStandardSurface1_0.geometry}
        material={blackMaterials[0]}
        scale={0.01}
      />
      <mesh
        name="The_Spot004_surfaceShader1_0"
        geometry={nodes.The_Spot004_surfaceShader1_0.geometry}
        material={blackMaterials[1]}
        scale={0.01}
      />

      {/* White body / black spots variant */}
      <mesh
        name="The_Spot004_aiStandardSurface2_0"
        geometry={nodes.The_Spot004_aiStandardSurface2_0.geometry}
        material={whiteMaterial}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/spot.glb");
